package org.sidao.jfinal.model;

import org.sidao.jfinal.model.BaseGithubproject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Githubproject extends BaseGithubproject<Githubproject> {
	public static final Githubproject dao = new Githubproject().dao();
}
