package org.sidao.jfinal.model;

import org.sidao.jfinal.model.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person();
}
