package org.sidao.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGithubproject<M extends BaseGithubproject<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}

	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setURL(java.lang.String URL) {
		set("URL", URL);
	}

	public java.lang.String getURL() {
		return getStr("URL");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public void setLANG(java.lang.String LANG) {
		set("LANG", LANG);
	}

	public java.lang.String getLANG() {
		return getStr("LANG");
	}

	public void setCOMMENT(java.lang.String COMMENT) {
		set("COMMENT", COMMENT);
	}

	public java.lang.String getCOMMENT() {
		return getStr("COMMENT");
	}

	public void setUPDATE(java.lang.String UPDATE) {
		set("UPDATE", UPDATE);
	}

	public java.lang.String getUPDATE() {
		return getStr("UPDATE");
	}

	public void setDESCRIPT(java.lang.String DESCRIPT) {
		set("DESCRIPT", DESCRIPT);
	}

	public java.lang.String getDESCRIPT() {
		return getStr("DESCRIPT");
	}

	public void setSTAR(java.lang.Integer STAR) {
		set("STAR", STAR);
	}

	public java.lang.Integer getSTAR() {
		return getInt("STAR");
	}

}
